/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'miyohide' at '15/11/14 18:58' with Gradle 2.6
 *
 * @author miyohide, @date 15/11/14 18:58
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
